
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://z3nth10n.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# Languages #
#############

languages: ["en", "es"]
exclude_from_localizations: ["js", "img", "css", "script", "scripts"]

#############
# HTML Head #
#############

lang: "en"
author: "z3nth10n"
title: "{ z3nth10n }"
keywords: "z3nth10n, dev"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/assets/bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000

me-img: "/img/author.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#2f1f1f"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 250

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "dev"

syntax-highlight: True

############
# Timeline #
############

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "z3nth10n@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/Z3nth10n-344166426434567"
    custom-class: ""
  - title: "twitter"
    url: "https://twitter.com/z3nth10n"
    custom-class: ""
  - title: "github"
    url: "https://github.com/z3nth10n"
    custom-class: ""
  - title: "instagram"
    url: "https://instagram.com/z3nth10n"
    custom-class: ""
  - title: "discord"
    url: "https://discord.com/users/208235269764284417"
    custom-class: ""
  - title: "telegram"
    url: "https://t.me/z3nth10n"
    custom-class: ""
  - title: "rss"
    url: "/feed.xml"
    custom-class: "fas"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: z3nth10n
keybase-in-social: false
keybase-in-footer: false

##########
# Emojis #
##########

emoji:
  format: emojione-png # default html
  ascii: false # default false
  shortname: true # default true
  src: "https://github.githubassets.com/images/icons/emoji/unicode" # defaults to "https://cdn.jsdelivr.net/emojione/assets/#{ext}"
  
############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: en, es 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

################################################################################

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "vendor"]

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate-v2
  - jemoji
  - jekyll-emoji
  - iconv
  - nokogiri
  - jekyll-twitter-plugin
# - jekyll-multiple-languages-plugin

##############################################################################################################################
#                                                          ONLY DEV
##############################################################################################################################

#############
# HTML Head #
#############

description: "Blog and website of z3nth10n, blogging mainly for tech."

################
# Introduction #
################

introduction-header: "Who am I?"
introduction: "I'm spanish developer since 2011. I like (and also, I'm a bit get used) to develop lonely, but I'm open to new oportunities and I invite you to collaborate with me if you are interested on my projects. See them scrolling down."

##############################
# Dynamic Text on the Header #
##############################

lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"
  
##############
# Navigation #
##############

select-language: "Select your language"

#########
# Posts #
#########

empty-post-list-caption: "Nothing here..."

############
# Timeline #
############

events:
  - image: "/img/timeline/high-school.png"
    date: "February 2019"
    description: "I started at high school"
    url: ""
  - image: "/img/timeline/job-finish.png"
    date: "December 2018"
    description: "I finished my higher vocational training"
    url: ""
  - image: "/img/timeline/caja.jpg"
    date: "November 2016"
    description: "I bought my second computer (my current one)!"
    url: ""
  - image: "/img/timeline/studying.png"
    date: "September 2016"
    description: "I started studying my higher vocational training"
    url: ""
  - image: "/img/timeline/graduated.png"
    date: "June 2016"
    description: "I finished at school and I created my first Unity3D team (and our first paid assets were published)"
    url: ""
  - image: "/img/timeline/domain.png"
    date: "May 2016"
    description: "I bought my first domain && used Cloudflare for first time"
    url: ""
  - image: "/img/timeline/git.png"
    date: "May 2016 - Today"
    description: "Since here I had been using Github (with Git) && Gitlab"
    url: ""
  - image: "/img/timeline/java.png"
    date: "August 2015"
    description: "I started writing my first Java code && MC plugins for Bukkit"
    url: "https://github.com/VintageDev-Nukes/SykoCode"
  - image: "/img/timeline/minecraft.png"
    date: "December 2014 - September 2015"
    description: "We formed a team to build a MC server!"
    url: ""
  - image: "/img/timeline/procedural.jpg"
    date: "July 2014"
    description: "I tried to do a prodecural terrain generation system (w/ Perlin Noise) in Unity3D"
    url: ""
  - image: "/img/timeline/unity3d.png"
    date: "November 2013"
    description: "I started with Unity3D (I switched into C#)"
    url: ""
  - image: "/img/timeline/default.png"
    date: "July 2013"
    description: "I joined Github!"
    url: ""
  - image: "/img/timeline/stackoverflow.png"
    date: "July 2013"
    description: "I joined Stackoverflow!"
    url: "https://stackoverflow.com/users/2466790/seazoux"
  - image: "/img/timeline/actionscript.png"
    date: "May 2013"
    description: "I tried to learn ActionScript (but I abandoned the idea)"
    url: "https://www.youtube.com/watch?v=t7Sh4BQlzXc"
  - image: "/img/timeline/c++.png"
    date: "April 2013"
    description: "I tried to learn C && C++ (and my first minigames in SMFL)!"
    url: "https://github.com/VintageDev-Nukes/SelfLearningCpp"
  - image: "/img/timeline/smf.png"
    date: "January 2013"
    description: "I started using SMF"
    url: ""
  - image: "/img/timeline/php-sql.png"
    date: "November 2012"
    description: "I started learning PHP && MySQL!"
    url: "https://github.com/VintageDev-Nukes/InfiJuegos"
  - image: "/img/timeline/redlaptop.jpg"
    date: "September 2012"
    description: "I bought my second laptop!"
    url: ""
  - image: "/img/timeline/vbnet.png"
    date: "July 2012 - November 2013"
    description: "During this peiod I had been coding in VB.NET"
    url: "https://github.com/VintageDev-Nukes/SEO-Calculator"
  - image: "/img/timeline/vbscript.png"
    date: "June 2012"
    description: "I started writing my first VBScript scripts"
    url: "https://github.com/VintageDev-Nukes/VBS-Launcher"
  - image: "/img/timeline/msdos.jpg"
    date: "May 2012"
    description: "I started writing my first Batch scripts"
    url: "https://github.com/VintageDev-Nukes/BATCH-Launcher"
  - image: "/img/timeline/html-js-css.png"
    date: "June 2011"
    description: "I started writing my first HTML, JS and CSS snippets"
    url: "https://github.com/VintageDev-Nukes/Spirate-n-Miscs"
  - image: "/img/timeline/youtube.png"
    date: "June 2011"
    description: "I joined YouTube (as a YouTuber) (my first account was AlvaroAlbox registered in February 2010)"
    url: "https://socialblade.com/youtube/user/ikillnukes4evertmb"
  - image: "/img/timeline/ehn.png"
    date: "May 2011"
    description: "I joined ElHacker.Net"
    url: "https://foro.elhacker.net/profiles/seazoux-u419740.html"
  - image: "/img/timeline/maxiuniverse.png"
    date: "August 2010"
    description: "I discovered Spirate (and how to use hostings) and I recreated MaxiUniverse!"
    url: "https://web.archive.org/web/20190221220205/http://maxiuniverse.activo.mx/"
  - image: "/img/timeline/spirate.jpg"
    date: "April 2010 - June 2010"
    description: "I created my first forum (MaxiUniverse)"
    url: "https://web.archive.org/web/20100524184651/http://maxiuniverse.superforo.net/"
  - image: "/img/timeline/taringa.png"
    date: "Q3 2009"
    description: "I joined Taringa!"
    url: ""
  - image: "/img/timeline/freerider2.png"
    date: "Mid 2009"
    description: "I started playing Free Rider 2!"
    url: ""
  - image: "/img/timeline/foroactivo.png"
    date: "September 2008"
    description: "I discovered Foroactivo!"
    url: ""
  - image: "/img/timeline/old-laptop.png"
    date: "June 2008"
    description: "My uncles bought me my first laptop then I could start using internet as a frequent user && tried to learn VB6!"
    url: ""
  - image: "/img/timeline/nintendo.png"
    date: "July 2007"
    description: "I had my first Nintendo DS!"
    url: ""
  - image: "/img/timeline/old-computer.jpg"
    date: "April 2003"
    description: "My parents bought me my first computer!"
    url: ""
  - image: "/img/timeline/born.png"
    date: "July 1998"
    description: "I was born!"
    url: ""
    
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "**z3nth10n** is a Spanish developer since 2011. He likes coding in Unity3D and C#. Also, he knows about front-end (HTML, CSS and JQuery) developing, back-end developing (PHP, SQL and C#) and system administration (Bash and Powershell). He is forming a new team called United Teamwork Association, [see they work at Github](https://github.com/uta-org). If you are interested in join this team, please, send him a message on the buttons below."

# Sections shown in the index page

pages_list:
  # About: 'about'
  'Last Social Media': 'last-social-media'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'