
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://z3nth10n.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "z3nth10n"
title: "{ z3nth10n }"
description: "Blog and website of z3nth10n, blogging mainly for tech."
keywords: "z3nth10n, dev"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/assets/bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/ricknmoty-avatar.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#2f1f1f"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 250

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "dev"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/high-school.png"
    date: "February 2019"
    description: "I started at high school"
  - image: "/img/timeline/job-finish.png"
    date: "December 2018"
    description: "I finished my higher vocational training"
  - image: "/img/timeline/caja.jpg"
    date: "November 2016"
    description: "I bought my second computer (my current one)!"
  - image: "/img/timeline/studying.png"
    date: "September 2016"
    description: "I started studying my higher vocational training"
  - image: "/img/timeline/graduated.png"
    date: "June 2016"
    description: "I finished at school and I created my first Unity3D team (and our first paid assets were published)"
  - image: "/img/timeline/git.png"
    date: "May 2016 - Today"
    description: "Since here I had been using Github (with Git) && Gitlab"
  - image: "/img/timeline/unity3d.png"
    date: "November 2013"
    description: "I started with Unity3D (I switched into C#)"
  - image: "/img/timeline/default.png"
    date: "July 2013"
    description: "I joined Github!"
  - image: "/img/timeline/redlaptop.jpg"
    date: "September 2012"
    description: "I bought my second laptop!"
  - image: "/img/timeline/vbnet.png"
    date: "July 2012 - November 2013"
    description: "During this peiod I had been coding in VB.NET"
  - image: "/img/timeline/vbscript.png"
    date: "June 2012"
    description: "I started writing my first VBScript scripts"
  - image: "/img/timeline/msdos.jpg"
    date: "May 2012"
    description: "I started writing my first Batch scripts"
  - image: "/img/timeline/html-js-css.png"
    date: "June 2011"
    description: "I started writing my first HTML, JS and CSS snippets"
  - image: "/img/timeline/spirate.jpg"
    date: "August 2010"
    description: "I discovered Spirate!"
  - image: "/img/timeline/foroactivo.png"
    date: "September 2008"
    description: "I discovered Foroactivo!"
  - image: "/img/timeline/old-laptop.png"
    date: "June 2008"
    description: "My uncles bought me my first laptop then I could start using internet as a frequent user && tried to learn VB6!"
  - image: "/img/timeline/nintendo.png"
    date: "July 2007"
    description: "I had my first Nintendo DS!"
  - image: "/img/timeline/old-computer.jpg"
    date: "April 2003"
    description: "My parents bought me my first computer!"
  - image: "/img/timeline/born.png"
    date: "July 1998"
    description: "I was born!"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "z3nth10n@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/Z3nth10n-344166426434567"
  - title: "twitter"
    url: "https://twitter.com/z3nth10n"
  - title: "github"
    url: "https://github.com/z3nth10n"
  - title: "instagram"
    url: "https://instagram.com/z3nth10n"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: z3nth10n
keybase-in-social: false
keybase-in-footer: false

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  # About: 'about'
  'Last Social Media': 'last-social-media'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "vendor"]

# Pagination path

paginate_path: "/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - iconv
  - nokogiri
  - jekyll-twitter-plugin
