# Jekyll Production Config

plugins:
  - jekyll-paginate-v2
  - jemoji
  - jekyll-emoji
  - iconv
  - nokogiri
  - jekyll-twitter-plugin
  - jekyll-language-plugin
  - jekyll-redirect-from
  - jekyll-minifier
  
# Uglifier Args
jekyll-minifier:
  uglifier_args:
    harmony: true